<?xml version="1.0" encoding="utf-8"?>
<!--
This file catalogues IDL syntax elements contained in
the IDL HTML documentation set.
Catalog created 16 Jun 2010
-->
<!DOCTYPE CATALOG [
   <!ELEMENT CATALOG (CLASS*, ROUTINE*, SYSVAR*, STATEMENT*)*>
   <!ATTLIST CATALOG name CDATA #IMPLIED>
   <!ATTLIST CATALOG version CDATA #IMPLIED>
   <!ELEMENT ROUTINE (SYNTAX | ARGUMENT | KEYWORD)*>
   <!ATTLIST ROUTINE name CDATA #IMPLIED>
   <!ATTLIST ROUTINE link CDATA #IMPLIED>
   <!ATTLIST ROUTINE alias_to CDATA #IMPLIED>
   <!ATTLIST ROUTINE classname CDATA #IMPLIED>
   <!ELEMENT STATEMENT EMPTY >
   <!ATTLIST STATEMENT name CDATA #IMPLIED>
   <!ATTLIST STATEMENT link CDATA #IMPLIED>
   <!ATTLIST STATEMENT alias_to CDATA #IMPLIED>
   <!ELEMENT SYNTAX EMPTY>
   <!ATTLIST SYNTAX name CDATA #IMPLIED>
   <!ATTLIST SYNTAX type CDATA #IMPLIED>
   <!ELEMENT ARGUMENT EMPTY>
   <!ATTLIST ARGUMENT name CDATA #IMPLIED>
   <!ATTLIST ARGUMENT link CDATA #IMPLIED>
   <!ELEMENT KEYWORD EMPTY>
   <!ATTLIST KEYWORD name CDATA #IMPLIED>
   <!ATTLIST KEYWORD link CDATA #IMPLIED>
   <!ELEMENT CLASS (SUPERCLASS*, PROPERTY*, METHOD*)>
   <!ATTLIST CLASS name CDATA #IMPLIED>
   <!ATTLIST CLASS link CDATA #IMPLIED>
   <!ELEMENT SUPERCLASS EMPTY>
   <!ATTLIST SUPERCLASS name CDATA #IMPLIED>
   <!ATTLIST SUPERCLASS link CDATA #IMPLIED>
   <!ELEMENT PROPERTY EMPTY>
   <!ATTLIST PROPERTY name CDATA #IMPLIED>
   <!ATTLIST PROPERTY link CDATA #IMPLIED>
   <!ATTLIST PROPERTY get CDATA #IMPLIED>
   <!ATTLIST PROPERTY set CDATA #IMPLIED>
   <!ATTLIST PROPERTY init CDATA #IMPLIED>
   <!ATTLIST PROPERTY registered CDATA #IMPLIED>
   <!ELEMENT METHOD (SYNTAX | ARGUMENT | KEYWORD)*>
   <!ATTLIST METHOD class CDATA #IMPLIED>
   <!ATTLIST METHOD name CDATA #IMPLIED>
   <!ATTLIST METHOD link CDATA #IMPLIED>
   <!ELEMENT ODOT_TAG EMPTY>
   <!ATTLIST ODOT_TAG name CDATA #IMPLIED>
   <!ELEMENT SYSVAR (FIELD*)>
   <!ATTLIST SYSVAR name CDATA #IMPLIED>
   <!ATTLIST SYSVAR link CDATA #IMPLIED>
   <!ATTLIST SYSVAR alias_to CDATA #IMPLIED>
   <!ELEMENT FIELD EMPTY>
   <!ATTLIST FIELD name CDATA #IMPLIED>
   <!ATTLIST FIELD link CDATA #IMPLIED>
]>
<CATALOG name="IDL" version="8.0">
  <ROUTINE name="Keywords" link="Keywords_Accepted_by_the.html">
    <KEYWORD name="AVANTGARDE" link="Keywords_Accepted_by_the.html#devices_517620971_482989" />
    <KEYWORD name="AVERAGE_LINES" link="Keywords_Accepted_by_the.html#devices_517620971_144491" />
    <KEYWORD name="BINARY" link="Keywords_Accepted_by_the.html#devices_517620971_144309" />
    <KEYWORD name="BITS_PER_PIXEL" link="Keywords_Accepted_by_the.html#devices_517620971_144308" />
    <KEYWORD name="BKMAN" link="Keywords_Accepted_by_the.html#devices_517620971_143940" />
    <KEYWORD name="BOLD" link="Keywords_Accepted_by_the.html#devices_517620971_144497" />
    <KEYWORD name="BOOK" link="Keywords_Accepted_by_the.html#devices_517620971_144499" />
    <KEYWORD name="BYPASS_TRANSLATION" link="Keywords_Accepted_by_the.html#devices_517620971_144256" />
    <KEYWORD name="CLOSE" link="Keywords_Accepted_by_the.html#devices_517620971_144712" />
    <KEYWORD name="CLOSE_DOCUMENT" link="Keywords_Accepted_by_the.html#devices_517620971_451438" />
    <KEYWORD name="CLOSE_FILE" link="Keywords_Accepted_by_the.html#devices_517620971_144158" />
    <KEYWORD name="CMYK" link="Keywords_Accepted_by_the.html#devices_517620971_732196" />
    <KEYWORD name="COLOR" link="Keywords_Accepted_by_the.html#devices_517620971_144479" />
    <KEYWORD name="COLORS" link="Keywords_Accepted_by_the.html#devices_517620971_144313" />
    <KEYWORD name="COPY" link="Keywords_Accepted_by_the.html#devices_517620971_143954" />
    <KEYWORD name="COURIER" link="Keywords_Accepted_by_the.html#devices_517620971_144503" />
    <KEYWORD name="CURSOR_CROSSHAIR" link="Keywords_Accepted_by_the.html#devices_517620971_144502" />
    <KEYWORD name="CURSOR_IMAGE" link="Keywords_Accepted_by_the.html#devices_517620971_143934" />
    <KEYWORD name="CURSOR_MASK" link="Keywords_Accepted_by_the.html#devices_517620971_144824" />
    <KEYWORD name="CURSOR_ORIGINAL" link="Keywords_Accepted_by_the.html#devices_517620971_144828" />
    <KEYWORD name="CURSOR_STANDARD" link="Keywords_Accepted_by_the.html#devices_517620971_144830" />
    <KEYWORD name="CURSOR_XY" link="Keywords_Accepted_by_the.html#devices_517620971_143722" />
    <KEYWORD name="DECOMPOSED" link="Keywords_Accepted_by_the.html#devices_517620971_144834" />
    <KEYWORD name="DEMI" link="Keywords_Accepted_by_the.html#devices_517620971_143930" />
    <KEYWORD name="DIRECT_COLOR" link="Keywords_Accepted_by_the.html#devices_517620971_145006" />
    <KEYWORD name="EJECT" link="Keywords_Accepted_by_the.html#devices_517620971_143752" />
    <KEYWORD name="ENCAPSULATED" link="Keywords_Accepted_by_the.html#devices_517620971_143751" />
    <KEYWORD name="ENCODING" link="Keywords_Accepted_by_the.html#devices_517620971_144315" />
    <KEYWORD name="FILENAME" link="Keywords_Accepted_by_the.html#devices_517620971_143748" />
    <KEYWORD name="FLOYD" link="Keywords_Accepted_by_the.html#devices_517620971_144833" />
    <KEYWORD name="FONT_INDEX" link="Keywords_Accepted_by_the.html#devices_517620971_143943" />
    <KEYWORD name="FONT_SIZE" link="Keywords_Accepted_by_the.html#devices_517620971_144522" />
    <KEYWORD name="GET_CURRENT_FONT" link="Keywords_Accepted_by_the.html#devices_517620971_144518" />
    <KEYWORD name="GET_DECOMPOSED" link="Keywords_Accepted_by_the.html#devices_517620971_554681" />
    <KEYWORD name="GET_FONTNAMES" link="Keywords_Accepted_by_the.html#devices_517620971_554610" />
    <KEYWORD name="GET_FONTNUM" link="Keywords_Accepted_by_the.html#devices_517620971_144326" />
    <KEYWORD name="GET_GRAPHICS_FUNCTION" link="Keywords_Accepted_by_the.html#devices_517620971_145007" />
    <KEYWORD name="GET_PAGE_SIZE" link="Keywords_Accepted_by_the.html#devices_517620971_587045" />
    <KEYWORD name="GET_PIXEL_DEPTH" link="Keywords_Accepted_by_the.html#devices_517620971_878857" />
    <KEYWORD name="GET_SCREEN_SIZE" link="Keywords_Accepted_by_the.html#devices_517620971_149759" />
    <KEYWORD name="GET_VISUAL_DEPTH" link="Keywords_Accepted_by_the.html#devices_517620971_452299" />
    <KEYWORD name="GET_VISUAL_NAME" link="Keywords_Accepted_by_the.html#devices_517620971_551382" />
    <KEYWORD name="GET_WINDOW_POSITION" link="Keywords_Accepted_by_the.html#devices_517620971_143947" />
    <KEYWORD name="GET_WRITE_MASK" link="Keywords_Accepted_by_the.html#devices_517620971_143949" />
    <KEYWORD name="GIN_CHARS" link="Keywords_Accepted_by_the.html#devices_517620971_143951" />
    <KEYWORD name="GLYPH_CACHE" link="Keywords_Accepted_by_the.html#devices_517620971_499334" />
    <KEYWORD name="HELVETICA" link="Keywords_Accepted_by_the.html#devices_517620971_144524" />
    <KEYWORD name="INCHES" link="Keywords_Accepted_by_the.html#devices_517620971_144166" />
    <KEYWORD name="INDEX_COLOR" link="Keywords_Accepted_by_the.html#devices_517620971_451483" />
    <KEYWORD name="ISOLATIN1" link="Keywords_Accepted_by_the.html#devices_517620971_144322" />
    <KEYWORD name="ITALIC" link="Keywords_Accepted_by_the.html#devices_517620971_143723" />
    <KEYWORD name="LANDSCAPE" link="Keywords_Accepted_by_the.html#devices_517620971_606950" />
    <KEYWORD name="LANGUAGE_LEVEL" link="Keywords_Accepted_by_the.html#devices_517620971_144167" />
    <KEYWORD name="LIGHT" link="Keywords_Accepted_by_the.html#devices_517620971_618160" />
    <KEYWORD name="MEDIUM" link="Keywords_Accepted_by_the.html#devices_517620971_144529" />
    <KEYWORD name="NARROW" link="Keywords_Accepted_by_the.html#devices_517620971_417784" />
    <KEYWORD name="NCAR" link="Keywords_Accepted_by_the.html#devices_517620971_144157" />
    <KEYWORD name="OBLIQUE" link="Keywords_Accepted_by_the.html#devices_517620971_562813" />
    <KEYWORD name="OPTIMIZE" link="Keywords_Accepted_by_the.html#devices_517620971_144405" />
    <KEYWORD name="ORDERED" link="Keywords_Accepted_by_the.html#devices_517620971_143941" />
    <KEYWORD name="OUTPUT" link="Keywords_Accepted_by_the.html#devices_517620971_144538" />
    <KEYWORD name="PALATINO" link="Keywords_Accepted_by_the.html#devices_517620971_144366" />
    <KEYWORD name="PIXELS" link="Keywords_Accepted_by_the.html#devices_517620971_144468" />
    <KEYWORD name="PLOT_TO" link="Keywords_Accepted_by_the.html#devices_517620971_485584" />
    <KEYWORD name="PLOTTER_ON_OFF" link="Keywords_Accepted_by_the.html#devices_517620971_144371" />
    <KEYWORD name="POLYFILL" link="Keywords_Accepted_by_the.html#devices_517620971_144368" />
    <KEYWORD name="PORTRAIT" link="Keywords_Accepted_by_the.html#devices_517620971_144170" />
    <KEYWORD name="PRE_DEPTH" link="Keywords_Accepted_by_the.html#devices_517620971_144169" />
    <KEYWORD name="PRE_XSIZE" link="Keywords_Accepted_by_the.html#devices_517620971_601831" />
    <KEYWORD name="PRE_YSIZE" link="Keywords_Accepted_by_the.html#devices_517620971_597448" />
    <KEYWORD name="PREVIEW" link="Keywords_Accepted_by_the.html#devices_517620971_601886" />
    <KEYWORD name="PRINT_FILE" link="Keywords_Accepted_by_the.html#devices_517620971_556886" />
    <KEYWORD name="PSEUDO_COLOR" link="Keywords_Accepted_by_the.html#devices_517620971_144688" />
    <KEYWORD name="RESET_STRING" link="Keywords_Accepted_by_the.html#devices_517620971_144455" />
    <KEYWORD name="RESOLUTION" link="Keywords_Accepted_by_the.html#devices_517620971_144473" />
    <KEYWORD name="RETAIN" link="Keywords_Accepted_by_the.html#devices_517620971_144472" />
    <KEYWORD name="SCALE_FACTOR" link="Keywords_Accepted_by_the.html#devices_517620971_144547" />
    <KEYWORD name="SCHOOLBOOK" link="Keywords_Accepted_by_the.html#devices_517620971_144551" />
    <KEYWORD name="SET_CHARACTER_SIZE" link="Keywords_Accepted_by_the.html#devices_517620971_486143" />
    <KEYWORD name="SET_COLORMAP" link="Keywords_Accepted_by_the.html#devices_517620971_161043" />
    <KEYWORD name="SET_COLORS" link="Keywords_Accepted_by_the.html#devices_517620971_486222" />
    <KEYWORD name="SET_FONT" link="Keywords_Accepted_by_the.html#devices_517620971_499045" />
    <KEYWORD name="SET_GRAPHICS_FUNCTION" link="Keywords_Accepted_by_the.html#devices_517620971_499029" />
    <KEYWORD name="SET_PIXEL_DEPTH" link="Keywords_Accepted_by_the.html#devices_517620971_144941" />
    <KEYWORD name="SET_RESOLUTION" link="Keywords_Accepted_by_the.html#devices_517620971_878877" />
    <KEYWORD name="SET_STRING" link="Keywords_Accepted_by_the.html#devices_517620971_144466" />
    <KEYWORD name="SET_TRANSLATION" link="Keywords_Accepted_by_the.html#devices_517620971_150093" />
    <KEYWORD name="SET_WRITE_MASK" link="Keywords_Accepted_by_the.html#devices_517620971_143957" />
    <KEYWORD name="STATIC_COLOR" link="Keywords_Accepted_by_the.html#devices_517620971_144842" />
    <KEYWORD name="STATIC_GRAY" link="Keywords_Accepted_by_the.html#devices_517620971_144844" />
    <KEYWORD name="SYMBOL" link="Keywords_Accepted_by_the.html#devices_517620971_144554" />
    <KEYWORD name="TEK4014" link="Keywords_Accepted_by_the.html#devices_517620971_144553" />
    <KEYWORD name="TEK4100" link="Keywords_Accepted_by_the.html#devices_517620971_144475" />
    <KEYWORD name="TEXT" link="Keywords_Accepted_by_the.html#devices_517620971_144841" />
    <KEYWORD name="THRESHOLD" link="Keywords_Accepted_by_the.html#devices_517620971_144376" />
    <KEYWORD name="TIMES" link="Keywords_Accepted_by_the.html#devices_517620971_144557" />
    <KEYWORD name="TRANSLATION" link="Keywords_Accepted_by_the.html#devices_517620971_144556" />
    <KEYWORD name="TRUE_COLOR" link="Keywords_Accepted_by_the.html#devices_517620971_883042" />
    <KEYWORD name="TT_FONT" link="Keywords_Accepted_by_the.html#devices_517620971_542703" />
    <KEYWORD name="TTY" link="Keywords_Accepted_by_the.html#devices_517620971_144477" />
    <KEYWORD name="USER_FONT" link="Keywords_Accepted_by_the.html#devices_517620971_574550" />
    <KEYWORD name="VT240" link="Keywords_Accepted_by_the.html#devices_517620971_144174" />
    <KEYWORD name="VT241" link="Keywords_Accepted_by_the.html#devices_517620971_868016" />
    <KEYWORD name="VT340" link="Keywords_Accepted_by_the.html#devices_517620971_144532" />
    <KEYWORD name="VT341" link="Keywords_Accepted_by_the.html#devices_517620971_868020" />
    <KEYWORD name="WINDOW_STATE" link="Keywords_Accepted_by_the.html#devices_517620971_144546" />
    <KEYWORD name="XOFFSET" link="Keywords_Accepted_by_the.html#devices_517620971_143719" />
    <KEYWORD name="XON_XOFF" link="Keywords_Accepted_by_the.html#devices_517620971_144379" />
    <KEYWORD name="XSIZE" link="Keywords_Accepted_by_the.html#devices_517620971_144540" />
    <KEYWORD name="YOFFSET" link="Keywords_Accepted_by_the.html#devices_517620971_144175" />
    <KEYWORD name="YSIZE" link="Keywords_Accepted_by_the.html#devices_517620971_144568" />
    <KEYWORD name="ZAPFCHANCERY" link="Keywords_Accepted_by_the.html#devices_517620971_144513" />
    <KEYWORD name="ZAPFDINGBATS" link="Keywords_Accepted_by_the.html#devices_517620971_144515" />
    <KEYWORD name="Z_BUFFERING" link="Keywords_Accepted_by_the.html#devices_517620971_144512" />
  </ROUTINE>
  <CLASS name="IDLanROI" link="IDLanROI.html">
    <SUPERCLASS name="None" link="" />
    <PROPERTY name="ALL" link="IDLanROI_Properties.html#objects_an_3393474575_1011351" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="BLOCK_SIZE" link="IDLanROI_Properties.html#objects_an_3393474575_1011320" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="DATA" link="IDLanROI_Properties.html#objects_an_3393474575_1011322" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="DOUBLE" link="IDLanROI_Properties.html#objects_an_3393474575_1011324" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="INTERIOR" link="IDLanROI_Properties.html#objects_an_3393474575_1011326" get="Yes" set="Yes" init="Yes" registered="No" />
    <PROPERTY name="N_VERTS" link="IDLanROI_Properties.html#objects_an_3393474575_1011660" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="ROI_XRANGE" link="IDLanROI_Properties.html#objects_an_3393474575_1011699" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="ROI_YRANGE" link="IDLanROI_Properties.html#objects_an_3393474575_1011726" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="ROI_ZRANGE" link="IDLanROI_Properties.html#objects_an_3393474575_1011728" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="TYPE" link="IDLanROI_Properties.html#objects_an_3393474575_1011328" get="Yes" set="No" init="Yes" registered="No" />
    <METHOD class="IDLanROI" name="IDLanROI::AppendData" link="IDLanROI__AppendData.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]AppendData, X [, Y] [, Z] [, XRANGE=variable] [, YRANGE=variable] [, ZRANGE=variable]" type="pro" />
      <ARGUMENT name="X" link="IDLanROI__AppendData.html" />
      <ARGUMENT name="Y" link="IDLanROI__AppendData.html" />
      <ARGUMENT name="Z" link="IDLanROI__AppendData.html" />
      <KEYWORD name="XRANGE" link="IDLanROI__AppendData.html#objects_an_3393474575_1003740" />
      <KEYWORD name="YRANGE" link="IDLanROI__AppendData.html#objects_an_3393474575_1003742" />
      <KEYWORD name="ZRANGE" link="IDLanROI__AppendData.html#objects_an_3393474575_1003744" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::Cleanup" link="IDLanROI__Cleanup.html">
      <SYNTAX name="Obj-&gt;Cleanup" type="pro" />
      <SYNTAX name="Obj-&gt;[IDLanROI::]Cleanup" type="pro" />
      <SYNTAX name="OBJ_DESTROY, Obj" type="pro" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::ComputeGeometry" link="IDLanROI__ComputeGeometr.html">
      <SYNTAX name="Result = Obj-&gt;[IDLanROI::]ComputeGeometry( [, AREA=variable] [, CENTROID=variable] [, PERIMETER=variable] [, SPATIAL_OFFSET=vector] [, SPATIAL_SCALE=vector] )" type="func" />
      <KEYWORD name="AREA" link="IDLanROI__ComputeGeometr.html#objects_an_3393474575_1003819" />
      <KEYWORD name="CENTROID" link="IDLanROI__ComputeGeometr.html#objects_an_3393474575_1003821" />
      <KEYWORD name="PERIMETER" link="IDLanROI__ComputeGeometr.html#objects_an_3393474575_1003823" />
      <KEYWORD name="SPATIAL_OFFSET" link="IDLanROI__ComputeGeometr.html#objects_an_3393474575_1003825" />
      <KEYWORD name="SPATIAL_SCALE" link="IDLanROI__ComputeGeometr.html#objects_an_3393474575_1003827" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::ComputeMask" link="IDLanROI__ComputeMask.html">
      <SYNTAX name="Result = Obj-&gt;[IDLanROI::]ComputeMask( [, INITIALIZE={ â€“1 | 0 | 1 }] [, DIMENSIONS=[xdim, ydim]] | [, MASK_IN=array] [, LOCATION=[x, y [, z]]] [, MASK_RULE={ 0 | 1 | 2 }] [, PIXEL_CENTER=[x, y]] [, PLANE_NORMAL=[x, y, z]] [, PLANE_XAXIS=[x,y,z]] [, /RUN_LENGTH] )" type="func" />
      <KEYWORD name="DIMENSIONS" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003872" />
      <KEYWORD name="INITIALIZE" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003874" />
      <KEYWORD name="LOCATION" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003879" />
      <KEYWORD name="MASK_IN" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003881" />
      <KEYWORD name="MASK_RULE" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003883" />
      <KEYWORD name="PIXEL_CENTER" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003888" />
      <KEYWORD name="PLANE_NORMAL" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1011165" />
      <KEYWORD name="PLANE_XAXIS" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003890" />
      <KEYWORD name="RUN_LENGTH" link="IDLanROI__ComputeMask.html#objects_an_3393474575_1003892" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::ContainsPoints" link="IDLanROI__ContainsPoints.html">
      <SYNTAX name="Result = Obj-&gt;[IDLanROI::]ContainsPoints( X [, Y [, Z]] )" type="func" />
      <ARGUMENT name="X" link="IDLanROI__ContainsPoints.html" />
      <ARGUMENT name="Y" link="IDLanROI__ContainsPoints.html" />
      <ARGUMENT name="Z" link="IDLanROI__ContainsPoints.html" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::GetProperty" link="IDLanROI__GetProperty.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]GetProperty [, PROPERTY=variable]" type="pro" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::Init" link="IDLanROI__Init.html">
      <SYNTAX name="Obj = OBJ_NEW( 'IDLanROI' [, X [, Y [, Z ]]] [, PROPERTY=value] )" type="func" />
      <SYNTAX name="Result = Obj-&gt;[IDLanROI::]Init( [X [, Y [, Z ]]] [, PROPERTY=value])     (In a lifecycle method only.)" type="func" />
      <ARGUMENT name="X" link="IDLanROI__Init.html" />
      <ARGUMENT name="Y" link="IDLanROI__Init.html" />
      <ARGUMENT name="Z" link="IDLanROI__Init.html" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::RemoveData" link="IDLanROI__RemoveData.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]RemoveData[, COUNT=vertices] [, START=index] [, XRANGE=variable] [, YRANGE=variable] [, ZRANGE=variable]" type="pro" />
      <KEYWORD name="COUNT" link="IDLanROI__RemoveData.html#objects_an_3393474575_1004077" />
      <KEYWORD name="START" link="IDLanROI__RemoveData.html#objects_an_3393474575_1004079" />
      <KEYWORD name="XRANGE" link="IDLanROI__RemoveData.html#objects_an_3393474575_1004081" />
      <KEYWORD name="YRANGE" link="IDLanROI__RemoveData.html#objects_an_3393474575_1004083" />
      <KEYWORD name="ZRANGE" link="IDLanROI__RemoveData.html#objects_an_3393474575_1004085" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::ReplaceData" link="IDLanROI__ReplaceData.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]ReplaceData, X[, Y[, Z]] [, START=index] [, FINISH=index] [, XRANGE =variable] [, YRANGE =variable] [, ZRANGE=variable]" type="pro" />
      <ARGUMENT name="X" link="IDLanROI__ReplaceData.html" />
      <ARGUMENT name="Y" link="IDLanROI__ReplaceData.html" />
      <ARGUMENT name="Z" link="IDLanROI__ReplaceData.html" />
      <KEYWORD name="FINISH" link="IDLanROI__ReplaceData.html#objects_an_3393474575_1004123" />
      <KEYWORD name="START" link="IDLanROI__ReplaceData.html#objects_an_3393474575_1004130" />
      <KEYWORD name="XRANGE" link="IDLanROI__ReplaceData.html#objects_an_3393474575_1004136" />
      <KEYWORD name="YRANGE" link="IDLanROI__ReplaceData.html#objects_an_3393474575_1004138" />
      <KEYWORD name="ZRANGE" link="IDLanROI__ReplaceData.html#objects_an_3393474575_1004140" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::Rotate" link="IDLanROI__Rotate.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]Rotate, Axis, Angle [, CENTER =[x, y[, z]]]" type="pro" />
      <ARGUMENT name="Axis" link="IDLanROI__Rotate.html" />
      <ARGUMENT name="Angle" link="IDLanROI__Rotate.html" />
      <KEYWORD name="CENTER" link="IDLanROI__Rotate.html#objects_an_3393474575_1004176" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::Scale" link="IDLanROI__Scale.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]Scale, Sx[, Sy[, Sz]]" type="pro" />
      <ARGUMENT name="Sx" link="IDLanROI__Scale.html" />
      <ARGUMENT name="Sy" link="IDLanROI__Scale.html" />
      <ARGUMENT name="Sz" link="IDLanROI__Scale.html" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::SetProperty" link="IDLanROI__SetProperty.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]SetProperty" type="pro" />
    </METHOD>
    <METHOD class="IDLanROI" name="IDLanROI::Translate" link="IDLanROI__Translate.html">
      <SYNTAX name="Obj-&gt;[IDLanROI::]Translate, Tx[, Ty[, Tz]]" type="pro" />
      <ARGUMENT name="Tx" link="IDLanROI__Translate.html" />
      <ARGUMENT name="Ty" link="IDLanROI__Translate.html" />
      <ARGUMENT name="Tz" link="IDLanROI__Translate.html" />
    </METHOD>
  </CLASS>
  <CLASS name="IDLanROIGroup" link="IDLanROIGroup.html">
    <SUPERCLASS name="IDL_Container" link="../../Reference Material/I/IDL_Container.html#objects_misc_904195448_1010504" />
    <PROPERTY name="ALL" link="IDLanROIGroup_Properties.html#objects_an_3393474575_1011995" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="ROIGROUP_XRANGE" link="IDLanROIGroup_Properties.html#objects_an_3393474575_1011998" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="ROIGROUP_YRANGE" link="IDLanROIGroup_Properties.html#objects_an_3393474575_1012000" get="Yes" set="No" init="No" registered="No" />
    <PROPERTY name="ROIGROUP_ZRANGE" link="IDLanROIGroup_Properties.html#objects_an_3393474575_1012002" get="Yes" set="No" init="No" registered="No" />
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::Add" link="IDLanROIGroup__Add.html">
      <SYNTAX name="Obj-&gt;[IDLanROIGroup::]Add, ROI" type="pro" />
      <ARGUMENT name="ROI" link="IDLanROIGroup__Add.html" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::Cleanup" link="IDLanROIGroup__Cleanup.html">
      <SYNTAX name="Obj-&gt;Cleanup" type="pro" />
      <SYNTAX name="Obj-&gt;[IDLanROIGroup::]Cleanup" type="pro" />
      <SYNTAX name="OBJ_DESTROY, Obj" type="pro" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::ComputeMask" link="IDLanROIGroup__ComputeMa.html">
      <SYNTAX name="Result = Obj-&gt;[IDLanROIGroup::]ComputeMask( [, INITIALIZE ={ â€‘1 | 0 | 1 }] [, DIMENSIONS =[xdim, ydim]] | [, MASK_IN =array] [, LOCATION =[x, y [, z]]] [, MASK_RULE={ 0 | 1 | 2 }] [, PLANE_NORMAL=[x, y, z]] [, PLANE_XAXIS=[x, y, z]] [, /RUN_LENGTH] )" type="func" />
      <KEYWORD name="DIMENSIONS" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004482" />
      <KEYWORD name="INITIALIZE" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004484" />
      <KEYWORD name="LOCATION" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004489" />
      <KEYWORD name="MASK_IN" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004491" />
      <KEYWORD name="MASK_RULE" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004493" />
      <KEYWORD name="PLANE_NORMAL" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004498" />
      <KEYWORD name="PLANE_XAXIS" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004500" />
      <KEYWORD name="RUN_LENGTH" link="IDLanROIGroup__ComputeMa.html#objects_an_3393474575_1004502" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::ComputeMesh" link="IDLanROIGroup__ComputeMe.html">
      <SYNTAX name="Result = Obj-&gt;[IDLanROIGroup::]ComputeMesh( Vertices, Conn [, CAPPED ={ 0 | 1 | 2}] [, SURFACE_AREA =variable] )" type="func" />
      <ARGUMENT name="Vertices" link="IDLanROIGroup__ComputeMe.html" />
      <ARGUMENT name="Conn" link="IDLanROIGroup__ComputeMe.html" />
      <KEYWORD name="CAPPED" link="IDLanROIGroup__ComputeMe.html#objects_an_3393474575_1004551" />
      <KEYWORD name="SURFACE_AREA" link="IDLanROIGroup__ComputeMe.html#objects_an_3393474575_1004556" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::ContainsPoints" link="IDLanROIGroup__ContainsP.html">
      <SYNTAX name="Result = Obj-&gt;[IDLanROIGroup::]ContainsPoints( X[, Y[, Z]] )" type="func" />
      <ARGUMENT name="X" link="IDLanROIGroup__ContainsP.html" />
      <ARGUMENT name="Y" link="IDLanROIGroup__ContainsP.html" />
      <ARGUMENT name="Z" link="IDLanROIGroup__ContainsP.html" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::GetProperty" link="IDLanROIGroup__GetProper.html">
      <SYNTAX name="Obj-&gt;[IDLanROIGroup::]GetProperty [, PROPERTY=value]" type="pro" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::Init" link="IDLanROIGroup__Init.html">
      <SYNTAX name="Obj = OBJ_NEW('IDLanROIGroup')" type="func" />
      <SYNTAX name="Result = Obj-&gt;[IDLanROIGroup::]Init( )      (In a lifecycle method only.)" type="func" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::Rotate" link="IDLanROIGroup__Rotate.html">
      <SYNTAX name="Obj-&gt;[IDLanROIGroup::]Rotate, Axis, Angle[, CENTER =[ x, y[, z ]] ]" type="pro" />
      <ARGUMENT name="Axis" link="IDLanROIGroup__Rotate.html" />
      <ARGUMENT name="Angle" link="IDLanROIGroup__Rotate.html" />
      <KEYWORD name="CENTER" link="IDLanROIGroup__Rotate.html#objects_an_3393474575_1004731" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::Scale" link="IDLanROIGroup__Scale.html">
      <SYNTAX name="Obj-&gt;[IDLanROIGroup::]Scale, Sx[, Sy[, Sz]]" type="pro" />
      <ARGUMENT name="Sx" link="IDLanROIGroup__Scale.html" />
      <ARGUMENT name="Sy" link="IDLanROIGroup__Scale.html" />
      <ARGUMENT name="Sz" link="IDLanROIGroup__Scale.html" />
    </METHOD>
    <METHOD class="IDLanROIGroup" name="IDLanROIGroup::Translate" link="IDLanROIGroup__Translate.html">
      <SYNTAX name="Obj-&gt;[IDLanROIGroup::]Translate, Tx[, Ty[, Tz]]" type="pro" />
      <ARGUMENT name="Tx" link="IDLanROIGroup__Translate.html" />
      <ARGUMENT name="Ty" link="IDLanROIGroup__Translate.html" />
      <ARGUMENT name="Tz" link="IDLanROIGroup__Translate.html" />
    </METHOD>
  </CLASS>
  <CLASS name="IDLffDICOM" link="IDLffDICOM.html">
    <SUPERCLASS name="None" link="" />
    <PROPERTY name="VERBOSE" link="IDLffDICOM_Properties.html#objects_ff_3755668711_1024027" get="No" set="No" init="" registered="No" />
    <METHOD class="IDLffDICOM" name="IDLffDICOM::Cleanup" link="IDLffDICOM__Cleanup.html">
      <SYNTAX name="Obj-&gt;Cleanup" type="pro" />
      <SYNTAX name="or" type="pro" />
      <SYNTAX name="Obj-&gt;[IDLffDICOM::]Cleanup" type="pro" />
      <SYNTAX name="or" type="pro" />
      <SYNTAX name="OBJ_DESTROY, Obj" type="pro" />
    </METHOD>
    <METHOD class="IDLffDICOM" name="IDLffDICOM::DumpElements" link="IDLffDICOM__DumpElements.html">
      <SYNTAX name="Obj-&gt;[IDLffDICOM::]DumpElements [, Filename]" type="pro" />
      <ARGUMENT name="Filename" link="IDLffDICOM__DumpElements.html" />
    </METHOD>
    <METHOD class="IDLffDICOM" name="IDLffDICOM::GetChildren" link="IDLffDICOM__GetChildren.html">
      <SYNTAX name="Result = Obj-&gt;[IDLffDICOM::]GetChildren(Reference)" type="func" />
      <ARGUMENT name="Reference" link="IDLffDICOM__GetChildren.html" />
    </METHOD>
    <METHOD class="IDLffDICOM" name="IDLffDICOM::GetDescription" link="IDLffDICOM__GetDescripti.html">
      <SYNTAX name="Result = Obj-&gt;[IDLffDICOM::]GetDescription([Group [, Element]] [, REFERENCE=list of element references])" type="func" />
      <ARGUMENT name="Group" link="IDLffDICOM__GetDescripti.html" />
      <ARGUMENT name="Element" link="IDLffDICOM__GetDescripti.html" />
      <KEYWORD name="REFERENCE" link="IDLffDICOM__GetDescripti.html#objects_ff_3755668711_1004342" />
    </METHOD>
    <METHOD class="IDLffDICOM" name="IDLffDICOM::GetElement" link="IDLffDICOM__GetElement.html">
      <SYNTAX name="Result = Obj-&gt;[IDLffDICOM::]GetElement([Group [, Element]] [, REFERENCE=list of element references])" type="func" />
      <ARGUMENT name="Group" link="IDLffDICOM__GetElement.html" />
      <ARGUMENT name="Element" link="IDLffDICOM__GetElement.html" />
      <KEYWORD name="REFERENCE" link="IDLffDICOM__GetElement.html#objects_ff_3755668711_1004397" />
    </METHOD>
    <METHOD class="IDLffDICOM" name="IDLffDICOM::GetGroup" link="IDLffDICOM__GetGroup.html">
      <SYNTAX name="Result = Obj-&gt;[IDLffDICOM::]GetGroup([Group[, Element]] [, REFERENCE=list of element references])" type="func" />
      <ARGUMENT name="Group" link="IDLffDICOM__GetGroup.html" />
      <ARGUMENT name="Element" link="IDLffDICOM__GetGroup.html" />
      <KEYWORD name="REFERENCE" link="IDLffDICOM__GetGroup.html#objects_ff_3755668711_1004455" />
    </METHOD>
    <METHOD class="IDLffDICOM" name="IDLffDICOM::GetLength" link="IDLffDICOM__GetLength.html">
      <SYNTAX name="Result = Obj-&gt;[IDLffDICOM::]GetLength([Group [, Element]] [, REFERENCE=list of element references])" type="func" />